### ISSUE TITLE
Cannot get Solarium work with Solr 5.1 or Solr 5.2

### ISSUE THREAD

**Issue by eostis** [solariumphp/solarium#340]
Hello,

I've just downloaded Solarium 3.4.0, and it solves the formats issues with Solr 5.0 :)

But, unfortunately,  I could not get it work with Solr 5.1 or Solr 5.2
```
Solr HTTP error: OK (400) {"error":{"msg":"Bad contentType for search handler :text/xml; charset=UTF-8 request={omitHeader=true&fl=*,score&start=0&q=*:*&json.nl=flat&wt=json&rows=0}","code":400}}
```

```java
org.apache.solr.common.SolrException: Bad contentType for search handler :text/xml; charset=UTF-8 request={omitHeader=true&fl=*,score&start=0&q=*:*&json.nl=flat&wt=json&rows=0}
	at org.apache.solr.request.json.RequestUtil.processParams(RequestUtil.java:73)
	at org.apache.solr.util.SolrPluginUtils.setDefaults(SolrPluginUtils.java:166)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:140)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:1984)
	at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:829)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:446)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:220)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:942)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

More generally, I could not find for which Solr versions Solarium is compatible with in documentation.

**Comment by eostis** [comment]
It appears that the fix #334 is not present in release 3.4.0.

I applied it manually on my own 3.4.0, and it worked.

Could you apply the fix in a new release ?

**Comment by basdenooijer** [comment]
Oops, seems like something has gone wrong with the merge there! Just created a 3.4.1 release that fixes this

**Comment by eostis** [comment]
Great!

Thanks.
