### ISSUE TITLE
Solarium\Exception\HttpException: Solr HTTP error: HTTP request failed, Operation timed out after 5001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by iamsayantan** [solariumphp/solarium#646]
I am getting timeout error while updating documents. Querying works fine and there is no issue with timeouts. Here is the stacktrace,

```
Solarium\Exception\HttpException: Solr HTTP error: HTTP request failed, Operation timed out after 5001 milliseconds with 0 bytes received in /var/www/app-v1.1/vendor/solarium/solarium/library/Solarium/Core/Client/Adapter/Curl.php:195
Stack trace:
#0 /var/www/app-v1.1/vendor/solarium/solarium/library/Solarium/Core/Client/Adapter/Curl.php(92): Solarium\Core\Client\Adapter\Curl->check('', Array, Resource id #15)
#1 /var/www/app-v1.1/vendor/solarium/solarium/library/Solarium/Core/Client/Adapter/Curl.php(213): Solarium\Core\Client\Adapter\Curl->getResponse(Resource id #15, false)
#2 /var/www/app-v1.1/vendor/solarium/solarium/library/Solarium/Core/Client/Adapter/Curl.php(68): Solarium\Core\Client\Adapter\Curl->getData(Object(Solarium\Core\Client\Request), Object(Solarium\Core\Client\Endpoint))
#3 /var/www/app-v1.1/vendor/solarium/solarium/library/Solarium/Core/Client/Client.php(804): Solarium\Core\Client\Adapter\Curl->execute(Object(Solarium\Core\Client\Request), Object(Solarium\Core\Client\Endpoint))
#4 /var/www/app-v1.1/vendor/solarium/solarium/library/Solarium/Core/Client/Client.php(773): Solarium\Core\Client\Client->executeRequest(Object(Solarium\Core\Client\Request), Object(Solarium\Core\Client\Endpoint))
#5 /var/www/app-v1.1/vendor/solarium/solarium/library/Solarium/Core/Client/Client.php(864): Solarium\Core\Client\Client->execute(Object(Solarium\QueryType\Update\Query\Query), NULL)
#6 /var/www/app-v1.1/app/Listeners/UserEventSubscriber.php(209): Solarium\Core\Client\Client->update(Object(Solarium\QueryType\Update\Query\Query))
#7 /var/www/app-v1.1/app/Listeners/UserEventSubscriber.php(146): App\Listeners\UserEventSubscriber->addUserToIndex(Object(App\User))
#8 [internal function]: App\Listeners\UserEventSubscriber->onUpdate(Object(App\Events\UserUpdate))
#9 /var/www/app-v1.1/bootstrap/cache/compiled.php(10332): call_user_func_array(Array, Array)
#10 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(App\Events\UserUpdate))
#11 /var/www/app-v1.1/bootstrap/cache/compiled.php(10266): call_user_func_array(Object(Closure), Array)
#12 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(480): Illuminate\Events\Dispatcher->fire('App\\Events\\User...')
#13 /var/www/app-v1.1/app/Http/Controllers/api/User.php(1538): event(Object(App\Events\UserUpdate))
#14 [internal function]: App\Http\Controllers\api\User->updateCurrentLocation(Object(App\Http\Requests\UserUpdateCurrentLocationRequest))
#15 /var/www/app-v1.1/bootstrap/cache/compiled.php(9584): call_user_func_array(Array, Array)
#16 /var/www/app-v1.1/bootstrap/cache/compiled.php(9611): Illuminate\Routing\Controller->callAction('updateCurrentLo...', Array)
#17 /var/www/app-v1.1/bootstrap/cache/compiled.php(8665): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\api\User), 'updateCurrentLo...')
#18 /var/www/app-v1.1/bootstrap/cache/compiled.php(8646): Illuminate\Routing\Route->runController()
#19 /var/www/app-v1.1/bootstrap/cache/compiled.php(8355): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/app-v1.1/app/Http/Middleware/LogoutBannedUsers.php(95): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/app-v1.1/bootstrap/cache/compiled.php(10069): App\Http\Middleware\LogoutBannedUsers->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/app-v1.1/bootstrap/cache/compiled.php(10177): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/app-v1.1/bootstrap/cache/compiled.php(10069): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/app-v1.1/bootstrap/cache/compiled.php(10069): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#29 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/app-v1.1/bootstrap/cache/compiled.php(10069): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#32 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/app-v1.1/bootstrap/cache/compiled.php(10054): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/app-v1.1/bootstrap/cache/compiled.php(8356): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /var/www/app-v1.1/bootstrap/cache/compiled.php(8347): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#36 /var/www/app-v1.1/bootstrap/cache/compiled.php(8338): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#37 /var/www/app-v1.1/bootstrap/cache/compiled.php(2575): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#38 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/app-v1.1/bootstrap/cache/compiled.php(3374): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/app-v1.1/bootstrap/cache/compiled.php(10069): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/app-v1.1/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/app-v1.1/bootstrap/cache/compiled.php(10069): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/app-v1.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/app-v1.1/bootstrap/cache/compiled.php(10054): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/app-v1.1/bootstrap/cache/compiled.php(2519): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /var/www/app-v1.1/bootstrap/cache/compiled.php(2503): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#48 /var/www/app-v1.1/public/index.php(55)
```
I have tried updating documents with curl from terminal and it works with the same kind of documents that are being updated from code.

**Comment by iamsayantan** [comment]
Hello, I found out that some process was hogging my cpu. Everything is working fine now.

**Comment by xemose** [comment]
I'm running into the same issue while updating documents. I'm updating 10,000 documents at a time and it's sending roughly 30,000 documents per second to solr. It works great for around 50 million documents then sometimes it'll crash. 

Is this because of cpu usage being too high?

**Comment by mkalkbrenner** [comment]
You have to set a higher timeout on the HTTP Adapter.
