### ISSUE TITLE
 Solr Exception: URLDecoder: Invalid character encoding detected after position 182 of query string

### ISSUE THREAD

**Issue by johnBHGW** [solariumphp/solarium#892]
**Solarium version(s) affected**: 4.1
**Solr version**:8.7

**Description**  
I am getting an Error thrown when I try to index documents on a stand alone SOLR server, from Ubuntu web server. The error message is as follows :

URL to be indexed:  /var/apps/vtleg/public/Documents/2016/Docs/BILLS/H-0039/H-0039 As Introduced.pdf  
Exception Message: Solr HTTP error: OK (500)
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /solr/vtleg/update/extract. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>org.apache.solr.common.SolrException: URLDecoder: Invalid character encoding detected after position 182 of query string / form data (while parsing as UTF-8)
	at org.apache.solr.servlet.SolrRequestParsers.decodeChars(SolrRequestParsers.java:421)
	at org.apache.solr.servlet.SolrRequestParsers.decodeBuffer(SolrRequestParsers.java:437)
	at org.apache.solr.servlet.SolrRequestParsers.parseFormDataContent(SolrRequestParsers.java:404)
	at org.apache.solr.servlet.SolrRequestParsers.parseQueryString(SolrRequestParsers.java:304)
	at org.apache.solr.servlet.SolrRequestParsers.parseQueryString(SolrRequestParsers.java:274)
	at org.apache.solr.servlet.HttpSolrCall.&lt;init&gt;(HttpSolrCall.java:181)
	at org.apache.solr.servlet.SolrDispatchFilter.getHttpSolrCall(SolrDispatchFilter.java:429)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:374)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:323)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.base/java.lang.Thread.run(Thread.java:834)
</pre>

</body>
</html>
<br/>

**How to reproduce**  
See [this](https://github.com/solariumphp/solarium/issues/888) issue for more details  about the servers configuration etc.....  

The error is thrown when the files at this particular location are attempted to be indexed using the following method

```
	public static function callSoleruim($doc_path, $properties) {
		// create a client instance
		$client = self::fetchClient();

		// get an extract query instance and add settings
		$query = $client->createExtract();
		$query->addFieldMapping('content', 'text');
		$query->setUprefix('attr_');
		$query->setFile($doc_path);
		$query->setCommit(true);
		$query->setOmitHeader(false);

		// add document
		$doc = $query->createDocument();
		foreach ($properties as $key => $property) {
			$doc->{$key} = $property;
		}
		$query->setDocument($doc);

		// this executes the query and returns the result
		try {
			$result = $client->extract($query);
	
			 echo "<b>Extract query executed</b><br/>\n";
			 print_r($properties, true);
			 echo 'Query status: ' . $result->getStatus(). "<br/>\n";
			 echo 'Query time: ' . $result->getQueryTime(). "<br/>\n";

			return true;

		} catch (Exception $e) {
			echo 'Exception Message: ' .$e->getMessage(). "<br/>\n";
			return false;
		}
	}
```

**Comment by thomascorthals** [comment]
Let me start of by saying that I personally try and use UTF-8 across the board for my projects: database collation, database connection, PHP's `default_charset` setting, PHP source files themselves, any assets of type `text/*`, any output I generate, all external API requests/responses that provide that option.

In your case specifically:
- database collation might be out of your control;
- you should make sure the charset for the database connection is set to UTF-8;
- `default_charset` is UTF-8 by default;
- Solr assumes incoming requests are UTF-8 unless told otherwise;
- Solr is only capable or returning responses in UTF-8;
- the encoding of the files you're trying to send doesn't actually matter for this error.

Most databases are capable of returning result values (and metadata such as column names) in UTF-8 even if they are stored in a different encoding. Check this first.

PHP has no concept of an internal encoding for strings. They aren't "tagged" as being UTF-8 or anything else, they're just a string of bytes (not characters) that you can pass around and manipulate. Some functions (e.g. `htmlspecialchars()`) do need to know according to which encoding they're supposed to interpret these bytes, that's where `default_charset` comes in. It doesn't hurt to check this as well.

I do notice that you're explicitly converting a string _from_ UTF-8 _to_ ISO-8859-1. What's the reason to do this? You're using the same string as-is in the next line.
```php
'literal.legislature_title' => iconv("UTF-8","ISO-8859-1//TRANSLIT", $file->Name),
'literal.legislature_file_title' => $file->Name,
```

The encoding of the HTML or PDF files you're trying to index isn't relevant because Solr offloads the extraction to Tika. Tika uses third party libraries for complex files that will probably try and get the encoding from embedded metadata. For plain text, it uses an encoding detector. This isn't influenced by or has any bearing on what Solr does with the remainder of your request.

If you do have to send a differently encoded request to Solr, it is possible to provide a `ie` (short for **i**nput **e**ncoding) parameter for GET requests or set a `Content-Type` header for POST requests. Starting with Solarium 6, you can use `$query->setInputEncoding('ISO-8859-1');` and don't have to worry about GET vs POST. #782 takes you through the nitty-gritty of this method. If you're stuck with an older version of Solarium, you're better off sticking with UTF-8.

**Comment by johnBHGW** [comment]
@thomascorthals Thank for your response to my inquiry, 
    I am the proud new owner of all of this code base, so it is sometimes hard for me to tell why some things were done and why. The previous developers are long gone, and documentation is .....
As far as I can tell the conversion to ISO-8859 from UTF-8 is done on a field that is used to display the name of a file that comes from a Windows environment, my best guess is that the original developer put it in there in two different encoding schemes to deal with the possibility of special characters coming from Windows to the Unix environment where SOLR is installed. The filenames are something that we don't have control over, there are a couple of competing naming macros in use. The company we support is consolidating into 1 macro, but we still have to support the old out of date naming conventions.
  So is it possible to catch the raw string that was sent to SOLR from somewhere, so I can see what the character was that broke Solr(Tika)?

Thanks again for all of the help. I really enjoy this product.

**Comment by thomascorthals** [comment]
Quick and dirty way to see what gets sent is dumping some info after the actual request is created:
https://github.com/solariumphp/solarium/blob/4dfd71fefb307cac1ec394b672f2f57256752e4b/src/Core/Client/Client.php#L757

```php
var_dump($request->getUri());
var_dump($request->getHeaders());
var_dump($request->getRawDate());
```

These will show the relative URI, request headers and POST data respectively.

**Comment by johnBHGW** [comment]
Here is the output of that request with those var_dump outputs, 
for URL: /var/apps/vtleg/public/Documents/2016/Docs/BILLS/H-0039/H-0039 As Introduced.pdf


string(670) "update/extract?omitHeader=false&wt=json&json.nl=flat&commit=true&uprefix=attr_&extractOnly=false&fmap.content=text&literal.name=786926&literal.literal.name=786926&literal.literal.legislature_title=An+act+relating+to+sales+of+ENERGY+STAR%AE+appliances&literal.literal.legislature_file_title=H-0039+As+Introduced.pdf&literal.literal.legislature_filename=Documents%2F2016%2FDocs%2FBILLS%2FH-0039%2FH-0039+As+Introduced.pdf&literal.literal.biennium=2016&literal.literal.legislature_category=bill&literal.literal.parent=H.39&literal.literal.related=&literal.literal.legislature_keywords=commerce+and+trade%2CEnergy+Star%C2%AE+appliances&resource.name=H-0039+As+Introduced.pdf"
array(1) {
  [0]=>
  string(76) "Content-Type: multipart/form-data; boundary=00000000776172db000000006870960e"
}
Exception Message: Solr HTTP error: OK (500)
<p>Problem accessing /solr/vtleg/update/extract. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>org.apache.solr.common.SolrException: URLDecoder: Invalid character encoding detected after position 182 of query string / form data (while parsing as UTF-8)
at org.apache.solr.servlet.SolrRequestParsers.decodeChars(SolrRequestParsers.java:421)
	at org.apache.solr.servlet.SolrRequestParsers.decodeBuffer(SolrRequestParsers.java:437)
	at org.apache.solr.servlet.SolrRequestParsers.parseFormDataContent(SolrRequestParsers.java:404)
	at org.apache.solr.servlet.SolrRequestParsers.parseQueryString(SolrRequestParsers.java:304)
	at org.apache.solr.servlet.SolrRequestParsers.parseQueryString(SolrRequestParsers.java:274)
	at org.apache.solr.servlet.HttpSolrCall.&lt;init&gt;(HttpSolrCall.java:181)
	at org.apache.solr.servlet.SolrDispatchFilter.getHttpSolrCall(SolrDispatchFilter.java:429)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:374)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:323)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.base/java.lang.Thread.run(Thread.java:834)
</pre>

</body>
</html>
<br/>

**Comment by thomascorthals** [comment]
My typo, sorry. `$request->getRawData()` (not 'rawDate'), I've corrected my comment above.

Doesn't matter because the problem is in the GET parameters.

```
update/extract?omitHeader=false&wt=json&json.nl=flat&commit=true&uprefix=attr_&extractOnly=false&fmap.content=text&literal.name=786926&literal.literal.name=786926&literal.literal.legislature_title=An+act+relating+to+sales+of+ENERGY+STAR%AE+appliances&literal.literal.legislature_file_title=H-0039+As+Introduced.pdf&literal.literal.legislature_filename=Documents%2F2016%2FDocs%2FBILLS%2FH-0039%2FH-0039+As+Introduced.pdf&literal.literal.biennium=2016&literal.literal.legislature_category=bill&literal.literal.parent=H.39&literal.literal.related=&literal.literal.legislature_keywords=commerce+and+trade%2CEnergy+Star%C2%AE+appliances&resource.name=H-0039+As+Introduced.pdf
               ^0        ^10       ^20       ^30       ^40       ^50       ^60       ^70       ^80       ^90       ^100      ^110      ^120      ^130      ^140      ^150      ^160      ^170        ^182    ^190      ^200
```

The problem is situated in the `literal.legislature_title` parameter.

```
literal.literal.legislature_title=An+act+relating+to+sales+of+ENERGY+STAR%AE+appliances
^148                              ^182
```

If we decode this back to an UTF-8 string (PHP's `default_charset`, and also what Solr does), we see that the character encoded as `%AE` is invalid (�). If we convert it from ISO-8859-1 to UTF-8 (which Solr doesn't do), it is valid (®);

```php
$title = urldecode('An+act+relating+to+sales+of+ENERGY+STAR%AE+appliances');

var_dump($title);
// string(51) "An act relating to sales of ENERGY STAR� appliances"

var_dump(iconv('ISO-8859-1', 'UTF-8', $title));
// string(52) "An act relating to sales of ENERGY STAR® appliances"
```

You'll notice that the invalid string has a length of 51 and the valid string of 52. That's because it reports the number of bytes in the string. � is a replacement character because `0xAE` is an invalid byte in UTF-8. The correct representation of ® is `0xC2 0xAE` and takes 2 bytes.

My advice: lose the `iconv()` and try again. If everything that comes from the database is UTF-8, it'll work. If it isn't, converting _from_ UTF-8 is the wrong way to fix it anyway.

**Comment by johnBHGW** [comment]
That works now, thank you
