### ISSUE TITLE
fix PHP 8.1 deprecation errors 

### ISSUE THREAD

**Issue by mkalkbrenner** [solariumphp/solarium#968]
https://github.com/solariumphp/solarium/runs/4635739307?check_suite_focus=true

```
PHP Deprecated:  http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /home/runner/work/solarium/solarium/src/Component/RequestBuilder/RequestParamsTrait.php on line 160

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /home/runner/work/solarium/solarium/src/Component/RequestBuilder/RequestParamsTrait.php on line 160
PHP Deprecated:  http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /home/runner/work/solarium/solarium/src/Component/RequestBuilder/RequestParamsTrait.php on line 160

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /home/runner/work/solarium/solarium/src/Component/RequestBuilder/RequestParamsTrait.php on line 160
PHP Deprecated:  Exception::__construct(): Passing null to parameter #2 ($code) of type int is deprecated in /home/runner/work/solarium/solarium/src/Exception/HttpException.php on line 70

Deprecated: Exception::__construct(): Passing null to parameter #2 ($code) of type int is deprecated in /home/runner/work/solarium/solarium/src/Exception/HttpException.php on line 70
Solarium\Exception\HttpException: Solr HTTP error: HTTP request failed, Operation timed out after 5001 milliseconds with 0 bytes received in /home/runner/work/solarium/solarium/src/Core/Client/Adapter/Curl.php:173
Stack trace:
#0 /home/runner/work/solarium/solarium/src/Core/Client/Adapter/Curl.php(63): Solarium\Core\Client\Adapter\Curl->check()
#1 /home/runner/work/solarium/solarium/src/Core/Client/Adapter/Curl.php(190): Solarium\Core\Client\Adapter\Curl->getResponse()
#2 /home/runner/work/solarium/solarium/src/Core/Client/Adapter/Curl.php(40): Solarium\Core\Client\Adapter\Curl->getData()
#3 /home/runner/work/solarium/solarium/src/Core/Client/Client.php(829): Solarium\Core\Client\Adapter\Curl->execute()
#4 /home/runner/work/solarium/solarium/src/Core/Client/Client.php(800): Solarium\Core\Client\Client->executeRequest()
#5 /home/runner/work/solarium/solarium/src/Core/Client/Client.php(1072): Solarium\Core\Client\Client->execute()
#6 /home/runner/work/solarium/solarium/examples/execute_all.php(39): Solarium\Core\Client\Client->configsets()
#7 {main}
```

**Comment by mkalkbrenner** [comment]
https://github.com/mkalkbrenner/search_api_solr/runs/4635904173?check_suite_focus=true

**Comment by VincentLanglet** [comment]
Hi @mkalkbrenner 
Can you create a new release with this deprecation fix ? Thanks you :)
